### ISSUE TITLE
Dynamic granaries

### ISSUE THREAD

**Issue by BeleGMRV** [Keriew/julius#10]
This is a suggestion to modify the behaviour of granaries to make them more efficient and intuitive by reducing the number of redundant intersections.  The gist of the idea is that granaries will only create the extra road bits required according to their position relative to adjacent roads (and some buildings), and none of the redundant ones it currently creates.  Let’s call them “dynamic granaries”.  The proposed changes would affect the gameplay and mess with saves, so Julius GC is a better home for this.

In vanilla C3, granaries always create an underlying “X” road design, with the central tile forming an intersection.  I would propose the following changes to that underlying road layout, which can be best exemplified with a comparison of current and desired behaviours:

![Granaries](https://user-images.githubusercontent.com/60972436/74774135-12f1f500-528b-11ea-9fc9-e07fef924ac4.png)

I think the above changes would make granaries more efficient, as we would get rid of all the inane walking-arounds inside the granary (and walkers would no longer get stuck in them / turn back).  They would also make them more intuitive, and would allow you to design granary placement in a way that you completely avoid undesired intersections (i.e. by placing them on a straight road or forming a V-turn).

One downside I can think of is that, if you make “unused” entrances inaccessible (i.e. you simply wall them), you would lose some of the flexibility of vanilla granaries in terms of allowing for clear paths through your city for destination walkers that don’t need roads (primarily warehouse cart pushers getting goods, but also others like military units).  It occurred to me that a way around this would be to transform those unused entrances (the yellow road bits in the above image) into roadblocks, rather than walling them, thus allowing those special walkers to go through the granary, but not allowing random walkers to venture into them.

Many thanks.

**Comment by Keriew** [comment]
Implemented with 95c8cfc . Only roaming walkers are affected.
