### ISSUE TITLE
Problem starting the game

### ISSUE THREAD

**Issue by ace197** [Keriew/julius#11]
Ask your question here.
Hi
how do i make your version work on my original caesar 3
I've tried different things
but have no experience with mods and can't make it work
carsten

**Comment by ace197** [comment]
And i’ve have the Julius version running btw

**Comment by Keriew** [comment]
Hey. I'll need more information. After unpacking all the files in the folder with Caesar 3 and running Juliusgc.exe what error do you get?

**Comment by ace197** [comment]
Hey 
No error ... your Updates just is not in the game 😩

**Comment by Keriew** [comment]
You need to download a separate executable - scroll down [here](https://github.com/Keriew/julius) download the latest version, unpack it in your Caesar 3 folder and run Juliusgc.exe.

**Comment by ace197** [comment]
OMG it worked  ... i missed you should download that file .... THANK YOU ... that's amazing what you did for that game ... Carsten from Denmark
