### ISSUE TITLE
Granaries getting food without a road connection

### ISSUE THREAD

**Issue by BeleGMRV** [Keriew/julius#12]
Warehouse cart pushers getting goods do not require a road connection between the two warehouses, whereas granary cart pushers always need one.  The suggestion is to make the “getting food” mechanic of granaries work more like the equivalent “getting goods” of warehouses by not requiring that road connection.

The need for a road connection can be a source of trouble when market buyer ladies decide to walk all the way to your “production” granaries in your farmland to buy food when the “distribution” granary is out of food (and they will sometimes do it even when there’s food there). We have all tried to avoid that issue by using warehouses to collect food in origin, transfer it somewhere else without a road connection and dump it in a granary on destination, but that feels a bit cheesy and is pretty inefficient.  The problem would go away if you simply cut the road connection between your housing and “distribution” granary, and your farmland and “production granary, and would help food distribution work a little better in maps like Lugdunum.

Many thanks.

**Comment by Keriew** [comment]
Implemented with de245f5.
