### ISSUE TITLE
Immediate building deletion as config option

### ISSUE THREAD

**Issue by crudelios** [Keriew/julius#14]
You know how, when you delete a building, you need to wait for a few in-game ticks before it actually disappears?
I always thought it made no sense, so I fixed it once. It was an one-liner but I don't really remember what I changed.

Anyway, it won't be implemented to base Julius (not even as an option), but I think it would be a nice little change for your fork.

If I remember the actual code change I'll post it here.

**Comment by Keriew** [comment]
Implemented.
