### ISSUE TITLE
Londinium Population Bug 

### ISSUE THREAD

**Issue by NeoXaero** [Keriew/julius#15]
I remember playing the Londinium map and building a huge city (12k pop or something like that) and then all new buildings that I placed wouldn't appear anymore.

I think that has something to do with integer limitation but I am not quite sure how it works.

There are few constants which are related to this
At least MAX_BUILDINGS, MAX_FIGURES, and MAX_ROUTES, but possibly more. Saving and loading files into account and test thoroughly.

**Comment by Keriew** [comment]
I intend to increase the game walker/building/etc. limits in the content update after the next one. That'll necessitate changing the file format so I want to think thoroughly and make all the changes I want to it at once.
