### ISSUE TITLE
Suggestion: Individual Shutdown of buildings

### ISSUE THREAD

**Issue by FenixR** [Keriew/julius#17]
A simple suggestion, might not be so simple in implementation.

Was thinking it would be nice to have an option to individually shutdown some buildings, specially non productions ones to control the worker population and the growth of homes.

**Comment by Keriew** [comment]
That's a good idea, I'll try to get it working soon.

**Comment by CommonLoon102** [comment]
I think such options was available in Caesar 4, very useful.
