### ISSUE TITLE
Change config crashes when clicking OK

### ISSUE THREAD

**Issue by theradeonxt** [Keriew/julius#33]
Found with latest source checkout from 27.04.2020

**Steps to reproduce**

1. Go into Options menu
2. Try to change an option - check something not yet enabled
3. Press OK to apply your changes
4. BUG: Game crashes with an exception:

![image](https://user-images.githubusercontent.com/13402104/80480307-14116380-8959-11ea-8a31-d8df95cd0e5b.png)

From what I see this function (change_action) is always 0x0, never set by anyone.

**Comment by Keriew** [comment]
That's really weird, it works fine for me. 

There's red underline under data, could you tell me what error does that give?

**Comment by LyonHe** [comment]
I am having the same issue, it seems like it crashs only if you changed your configs.
