### ISSUE TITLE
Warehouse bug ?

### ISSUE THREAD

**Issue by Mathonal** [Keriew/julius#34]
Hi guys, (great work on this augustus version, i am having fun)

I might have spotted a weird thing on warehouse behaviour :

It seems that, when a warehouse has orders to "get goods" from another **non-connected by road** warehouse, it will never get more than a quarter of full capacity (whatever option on quantity you set). After that, cart sits on its thumbs until warehouse is empty and it can fetch 8 goods again... 
if you order to "get goods" on two kinds of products, again, it will get max 8 products of each, and then do nothing. 

If it helps to pinpoint the problem, note that when the two warehouses are connected by road, the "get goods" behaviour works as intended with quantities set)

does anybody else have seen this ? for now, whenever i see a warehouse like that, i compensate by opening 4types of goods to use the thing to the fullest but i'd rather have the intended behaviour

Thanks for your time ;)

**Comment by Keriew** [comment]
Hey, that's how getting worked in C3. It's already changed for the next version with fda1695.
