### ISSUE TITLE
Application was unable to start Win10

### ISSUE THREAD

**Issue by theradeonxt** [Keriew/julius#7]
Hello,

I wanted to try your version with changes (global employment), and encountered a problem.

**Steps to reproduce:**

- Download julius original, I used latest 1.2.0: 
https://bintray.com/bvschaik/julius/windows-unstable/1.2.0.112-747ec334#files
- Make first configuration to find original C3 files
- Download julius + GC, I used 101: 
https://bintray.com/keriew/JuliusGC/windows_release
- Copy juliusgc.exe over in same folder where I had julius.exe
- Try to start juliusgc.exe:
- BUG: Get this error:
![image](https://user-images.githubusercontent.com/13402104/74239600-d3eaff00-4ce0-11ea-8777-47d34e519a4c.png)

Is there something I'm doing wrong?
Thanks, appreaciate you guys' work :)

**Comment by Keriew** [comment]
Okay, I see the problem. Main Julius and my fork use different SDL versions, so if you use the base Julius SDL2 and SDL2_mixer dlls (or my fork's with base Julius) it will cause this error. Try to use the dlls included in juliusgc.zip and tell me if that works. I'll try to fix the problem in the next release so you don't have to swap between them for main Julius and my fork.

**Comment by theradeonxt** [comment]
Damn, I had not noticed the sizes are different :(
Now it works. Many thanks!

![image](https://user-images.githubusercontent.com/13402104/74244995-f97d0600-4cea-11ea-9762-52c1b2e99beb.png)

**Comment by Keriew** [comment]
Will be fixed for the next release.
