### ISSUE TITLE
Faster scroll speed for high resolutions?

### ISSUE THREAD

**Issue by SilverSight1** [Keriew/julius#8]
I'm playing on a 2160x1440 monitor and if I enable smooth scrolling the scrolling speed is noticeably much slower. On 100% it's tolerable, but was wondering if you could increase the cap to something like 150%.

**Comment by SilverSight1** [comment]
Actually I'm not really sure if it's resolution related. I usually use 90% speed then switched to smooth and 100% doesn't reach the same level.

**Comment by crudelios** [comment]
I'll improve this oneon base Julius.
